version: '3.4'

services:
  kali:
    build: .
    restart: "no"

  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    env_file: ./services/.env

  wp-cli:
    image: bozdoz/wordpress-initialize
    env_file: ./services/.env
    depends_on:
      - db
    volumes: 
      - wp_data:/var/www/html
      - ./services/initialize-wp.sh:/app/initialize.sh

  wordpress:
    depends_on:
      - wp-cli
    build:
      context: ./services
      dockerfile: wordpress.ssl.Dockerfile
    volumes:
      - wp_data:/var/www/html
    ports:
      - "80:80"
      - "443:443"
    restart: always
    env_file: ./services/.env

  bwapp:
    build:
      context: ./services
      dockerfile: bwapp.Dockerfile
    ports:
      - "4600:4600"
    restart: always

volumes:
  db_data: {}
  wp_data: {}