#!/bin/bash

if [ -z "$1" ]; then
    echo "Error: missing path argument. Please provide file path. List can be found in: https://github.com/danielmiessler/SecLists";
    exit 1;
fi

FILE_PATH=$1

OUTPUT=$(curl https://raw.githubusercontent.com/danielmiessler/SecLists/master/$FILE_PATH)

if [ -z "$2" ]; then
    echo "$OUTPUT";
    exit 0;
fi

echo "$OUTPUT" >> $2

