#!/bin/bash

declare -A LISTS_REPOS=( [seclists]="https://github.com/danielmiessler/SecLists/tree/master/Passwords" 
                        [dirb]="https://github.com/v0re/dirb/tree/master/wordlists" )

while getopts l:f: flag
do
    case "${flag}" in
        l) LIST_URL=${OPTARG};;
        f) SAVE_TO_FILE=${OPTARG};;
    esac
done

if [ -z ${LIST_URL+x} ]; then
    echo "Use this command to download lists.
    Arguments:
    -l    List file url. Use raw display link
    -f    (optional) file path to save the content to. if not defined, the content will be displayed in console.";
    
    echo "Recomended lists by packages:";
    for K in "${!LISTS_REPOS[@]}"; do echo $K --- ${LISTS_REPOS[$K]}; done
    exit 0;
fi

OUTPUT=$(curl $LIST_URL)

if [ -z ${SAVE_TO_FILE+x} ]; then
    echo "$OUTPUT";
    exit 0;
fi

echo "$OUTPUT" >> $SAVE_TO_FILE

