#!/bin/bash

declare -A LISTS_REPOS=( [seclists]="https://api.github.com/repos/danielmiessler/SecLists/contents" 
                        [dirb]="https://api.github.com/repos/v0re/dirb/contents/wordlists" )

while getopts p:r: flag
do
    case "${flag}" in
        r) REPO_NAME=${OPTARG};;
        p) FILE_PATH=${OPTARG};;
    esac
done

if [ -z ${REPO_NAME+x} ]; then
    echo "Please specify the repository name to list.
    Arguments:
    -r    Repository name
    -p    (optional) path inside the repo";
    
    echo "Available lists:";
    for K in "${!LISTS_REPOS[@]}"; do echo "name: $K. content api url: ${LISTS_REPOS[$K]}"; done
    echo "To download list and append to file use: curl [REMOTE FILE PATH] >> [LOCAL FILE TO WRITE]"
    exit 0;
fi

URLPATH="${LISTS_REPOS[$REPO_NAME]}";

if [ ! -z ${FILE_PATH+x} ]; then
    URLPATH+="/${FILE_PATH}"
fi

OUTPUT=$(curl -H "Accept: application/vnd.github.v3+json" ${URLPATH}  | jq '.[] | {path: .path, download_url: .download_url}');

echo "$OUTPUT"

